# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-json
      exclude: '.vscode/'
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.28.1
  hooks:
    - id: markdownlint
      args: [ "--fix", "--config", ".markdownlint.yaml" ]
