version: '3.4'

services:
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: "prom/prometheus"
    restart: always
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=10y
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  blackbox-exporter:
    image: "prom/blackbox-exporter"
    restart: always
    ports:
      - 9115:9115
    command:
      - --config.file=/blackbox.yml
    volumes:
      - ./blackbox.yml:/blackbox.yml:ro

volumes:
  grafana-storage:
  prometheus-storage:
