scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module:
        - http
        - tcp_tls
    static_configs:
      - targets:
        - https://docs.nomupay.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.27.55.66:9115