# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
        exclude: \.svg$
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character
        exclude: \.svg$
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        exclude: mkdocs.yml
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python.git
    rev: 2.6.1
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: [ "--fix", "--config", ".markdownlint.json" ]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.19.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
