{
 "title": "blackbox-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "ICMP Probe Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(probe_success{job=\"blackbox-icmp\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg(sum(probe_icmp_duration_seconds) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Probe Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(probe_success{job=\"blackbox-http\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Average Request Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(sum(probe_http_duration_seconds) by (instance))"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Lookup Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Request Time - LOG2",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "log2(sum(probe_http_duration_seconds) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}